from . import regions
from . import property
from . import crm_team
from . import loan_line
from . import sale_order
from . import res_company
from . import repair_order
from . import property_extra
from . import account_payment
from . import account_invoice
from . import attachment_line
from . import project_worksite
from . import sales_commission
from . import property_contract
from . import res_config_settings
from . import property_reservation
from . import installment_template
from . import project_worksite_extra
from . import res_users
